### ISSUE TITLE
Protocol Recommendation Between Miners and Proxy

### ISSUE THREAD

**Issue by computeronix** [Stratehm/stratum-proxy#40]
Quick question, what protocol would you recommend between the miners and the proxy (local area network, not traversing internet, where the proxy will traverse the internet with extra nounce over stratum)

Stratum or Getwork?

Looking online I have seen various threads point between the two.

**Comment by Stratehm** [comment]
When using this proxy, I really recommand to use stratum as it is really less CPU intensive, more tested and easier to debug.

But this answer is only relevant for this proxy, it is not a general answer to the question of which from Stratum or getwork is better. (Even if I would say Stratum is better since Getwork is now considered as obsolete).

**Comment by computeronix** [comment]
Thanks!
