### ISSUE TITLE
Log Number of Shares Per Worker

### ISSUE THREAD

**Issue by MegaFall** [Stratehm/stratum-proxy#42]
Does this have the ability to log shares per worker into a database before they're forwarded to the pool, which I could then pull using PHP to show on a website? I'm just looking to log the number of shares submitted with the worker name.

Also, for a feature request, would it be possible to add load balancing to the pool selection (in addition to fail-over and round robin)? Selectable in 10% increments, where you point to two pools at once. Say 40% of the proxies hashrate to one pool and 60% of the hashrate to the other, as one example.

**Comment by Stratehm** [comment]
I will add the number of shares submitted by a user since the proxy startup in the following API method:
http://proxyIp:8888/user/list
(look at the API detail in the README file for more details)

Load-balancing will not be implemented in the proxy since the only way to do it is heavily inaccurate and ineffective (the hashing power of a single worker cannot be split over several pools).

**Comment by Stratehm** [comment]
Share numbers added to the user/list API method (5273df5f)
