### ISSUE TITLE
Vardiff with multiple different miners

### ISSUE THREAD

**Issue by michelem09** [Stratehm/stratum-proxy#50]
Hi,
thanks for the great work, I have this problem, I'd like to stratum proxy multiple different devices with really different difficulty to one single pool.
When my first device (for example with a value of 16 for difficulty) connect to the proxy there isn't any problem, but as soon as I connect a different miner (with for example 512 for difficulty) the first miner get this last difficulty and cannot mine anymore.
Is there something I miss?

**Comment by Stratehm** [comment]
The proxy established only one connection to the pool. Thus, all workers are mutualized on this single connection and the pool think it is a single miner. The hashrate of the all the miners connected to the proxy are added. 
So, if vardiff is enable on the pool, it adjusts the difficulty to the total hashrate. Your small miner still mines but will find less shares. But statistically, there is absolutely no loss (since each share worth more).

**Comment by michelem09** [comment]
Yes, you are right but I'd prefer to have multiple connections for each miner or pool of miners to have each one the right difficulty.
Well, no problem, thank you.

**Comment by mooleshacat** [comment]
Can the worksize not be split by the proxy? Other proxies will take this 25 diff and split it to the miners...

So you give the miners individual difficulties and they submit to the proxy which should by design join those shares into one large share and send it to the pool... That is the definition of a proxy when it comes to mining. It combines the connections and shares into one.
